### ISSUE TITLE
NullPointerException after LwM2M Client registration when  CongestionControl is active

### ISSUE THREAD

**Issue by JaroslawLegierski** [eclipse-californium/californium#2093]
We implemented Californium Congestion Control in Leshan server

```java
Configuration coapConfig = LeshanServerBuilder.createDefaultCoapConfiguration();
coapConfig.set(CoapConfig.CONGESTION_CONTROL_ALGORITHM, CoapConfig.CongestionControlMode.COCOA);
```
During registration new LwM2M client we observing following java.lang.NullPointerException:

```sh
2022-12-04 17:12:13,457 RegistrationHandler  [DEBUG] New registration: Registration [registrationDate=Sun Dec 04 17:12:13 CET 2022, identity=Identity /80.238.125.119:51704[psk=leshan11111], lifeTimeInSec=400, smsNumber=null, lwM2mVersion=1.1, bindingMode=[U], queueMode=false, endpoint=leshan11111, id=DaeoIsbPfC, objectLinks=[</>;rt=[oma.lwm2m];ct=[CBOR(60), SENML_JSON(110), SENML_CBOR(112), TLV(11542), JSON(11543)], </1>;ver=1.1, </1/0>, </3>;ver=1.2, </3/0>, </6/0>, </3303>;ver=1.1, </3303/0>, </3442/0>], additionalRegistrationAttributes={}, rootPath=/, supportedContentFormats=[TLV(11542), JSON(11543), LINK(40), OPAQUE(42), CBOR(60), SENML_JSON(110), SENML_CBOR(112), TEXT(0)], supportedObjects={1=1.1, 3442=1.0, 3=1.2, 6=1.0, 3303=1.1}, availableInstances=[/1/0, /3/0, /6/0, /3303/0, /3442/0], lastUpdate=Sun Dec 04 17:12:13 CET 2022, applicationData={}]
2022-12-04 17:12:13,475 BaseCoapStack        [WARN] error send response null-2.01   MID=   -1, Token=null, OptionSet={"Location-Path":["rd","DaeoIsbPfC"]}, <empty data>
java.lang.NullPointerException: null
	at org.eclipse.californium.core.network.stack.CongestionControlLayer.getRemoteEndpoint(CongestionControlLayer.java:205)
	at org.eclipse.californium.core.network.stack.CongestionControlLayer.sendResponse(CongestionControlLayer.java:486)
	at org.eclipse.californium.core.network.stack.BlockwiseLayer.sendResponse(BlockwiseLayer.java:760)
	at org.eclipse.californium.core.network.stack.ObserveLayer.sendResponse(ObserveLayer.java:140)
	at org.eclipse.californium.core.network.stack.AbstractLayer.sendResponse(AbstractLayer.java:74)
	at org.eclipse.californium.core.network.stack.ExchangeCleanupLayer.sendResponse(ExchangeCleanupLayer.java:95)
	at org.eclipse.californium.core.network.stack.BaseCoapStack$StackTopAdapter.sendResponse(BaseCoapStack.java:194)
	at org.eclipse.californium.core.network.stack.BaseCoapStack.sendResponse(BaseCoapStack.java:101)
	at org.eclipse.californium.core.network.CoapEndpoint.sendResponse(CoapEndpoint.java:720)
	at org.eclipse.californium.core.network.Exchange.sendResponse(Exchange.java:503)
	at org.eclipse.californium.core.server.resources.CoapExchange.respond(CoapExchange.java:539)
	at org.eclipse.californium.core.server.resources.CoapExchange.respond(CoapExchange.java:355)
	at org.eclipse.leshan.server.californium.registration.RegisterResource.handleRegister(RegisterResource.java:191)
	at org.eclipse.leshan.server.californium.registration.RegisterResource.handlePOST(RegisterResource.java:104)
	at org.eclipse.californium.core.CoapResource.handleRequest(CoapResource.java:261)
	at org.eclipse.leshan.core.californium.LwM2mCoapResource.handleRequest(LwM2mCoapResource.java:51)
	at org.eclipse.californium.core.server.ServerMessageDeliverer.deliverRequest(ServerMessageDeliverer.java:133)
	at org.eclipse.californium.core.network.stack.BaseCoapStack$StackTopAdapter.receiveRequest(BaseCoapStack.java:204)
	at org.eclipse.californium.core.network.stack.AbstractLayer.receiveRequest(AbstractLayer.java:84)
	at org.eclipse.californium.core.network.stack.AbstractLayer.receiveRequest(AbstractLayer.java:84)
	at org.eclipse.californium.core.network.stack.BlockwiseLayer.receiveRequest(BlockwiseLayer.java:556)
	at org.eclipse.californium.core.network.stack.ReliabilityLayer.receiveRequest(ReliabilityLayer.java:296)
	at org.eclipse.californium.core.network.stack.AbstractLayer.receiveRequest(AbstractLayer.java:84)
	at org.eclipse.californium.core.network.stack.BaseCoapStack.receiveRequest(BaseCoapStack.java:126)
	at org.eclipse.californium.core.network.CoapEndpoint$1.receiveRequest(CoapEndpoint.java:307)
	at org.eclipse.californium.core.network.UdpMatcher$2.run(UdpMatcher.java:289)
	at org.eclipse.californium.elements.util.SerialExecutor$1.run(SerialExecutor.java:293)
	at org.eclipse.californium.core.network.CoapEndpoint$6.run(CoapEndpoint.java:1364)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
2022-12-04 17:12:13,476 Exchange             [DEBUG] Exchange[R1, 80.238.125.119:51704, complete]!
2022-12-04 17:12:13,476 Exchange             [DEBUG] remote Exchange[R1, 80.238.125.119:51704, complete] rejected (without response)!
2022-12-04 17:12:13,480 InMemoryConnectionStore [DEBUG] connection: CID=5C051598B2A1 updated usage!
2022-12-04 17:12:13,558 EventServlet         [DEBUG] Dispatching REGISTRATION event from endpoint leshan11111
```
On client site we see following information:
```sh
                  LeshanClient 2022-12-04 17:12:12,000 [INFO] Starting Leshan client ...
   CaliforniumEndpointsManager 2022-12-04 17:12:12,828 [INFO] New endpoint created for server coaps://90.84.174.61:5684 at coaps://0.0.0.0:51704
                  LeshanClient 2022-12-04 17:12:12,830 [INFO] Leshan client[endpoint:leshan11111] started.
     DefaultRegistrationEngine 2022-12-04 17:12:12,830 [INFO] Trying to register to coaps://90.84.174.61:5684 ...
              LeshanClientDemo 2022-12-04 17:12:12,922 [INFO] DTLS Full Handshake initiated by client : STARTED ...
              LeshanClientDemo 2022-12-04 17:12:13,351 [INFO] DTLS Full Handshake initiated by client : SUCCEED
     DefaultRegistrationEngine 2022-12-04 17:12:13,506 [INFO] Unable to send register request : Request coap://90.84.174.61:5684/rd?b=U&lwm2m=1.1&lt=400&ep=leshan11111 rejected
     DefaultRegistrationEngine 2022-12-04 17:12:13,507 [INFO] Try to register to coaps://90.84.174.61:5684 again in 600s...
```
We are using Californium in version 3.7.0

Please find captured packets in attached  [client_packets.zip](https://github.com/eclipse-californium/californium/files/10149007/client_packets.zip) file

When congestion control is off - everything works correctly

**Comment by boaks** [comment]
I guess, the tests don't cover the responses ;-(.
I will not be able to work on this before next week.
Generally, beside of keeping the messages in a "in memory queue" in order to throttle the transmission for "constrained networks", there are no additional functions to maintain that queue. Keep that in mind, when using it.

I use mainly the responses on application level to achieve the NSTART-1 behavior, because for me that's more flexible.

**Comment by JaroslawLegierski** [comment]
Today I made some tests using real device Thingy91 from Nordic. Please find results in  attached files:  

[thingy91pcap.zip](https://github.com/eclipse-californium/californium/files/10193170/thingy91pcap.zip)
[trace_server.zip](https://github.com/eclipse-californium/californium/files/10193172/trace_server.zip)
Maybe this will help with Cf congestion controll diagnosis.

**Comment by boaks** [comment]
Thanks!

The traces demonstrates an additional issue:
If always a handshake is used, that for sure limits your bandwidth!
Not sure, I guess the 75 bytes application data in the capture is an error response.
(You may check that with your PSK secret, see [Decrypt messages for PSK Cipher Suites](https://github.com/eclipse-californium/californium/wiki/Logs-and-IP-Capturing-%E2%80%90-How-To-Provide-The-Right-Information#decrypt-messages-for-psk-cipher-suites) how to apply that secret to wireshark).
So it's possible, that the error response is causing the handshakes. 
Do you see these handshakes also without congestion control? 

(I use RFC 9146, see [zephyr-coaps-client - tinydtls](https://github.com/boaks/zephyr-coaps-client).
mbedtls has recently also merged the RFC9146 support, so maybe you also ask zephyr and nordic to go for it.)

> Maybe this will help with Cf congestion controll diagnosis.

Not really. My diagnose was, that the code miss to set the current response before calling `getRemoteEndpoint`.
I don't want to add just a "set", I prefer to check, if `getRemoteEndpoint` could be implemented in a slightly different way (no `Exchange` as parameter).

Anyway:
The `NullPointerExcpetion` must be fixed. With that, the error response will be gone.
But still such a in memory congestion control queue is only useful to store messages for a short couple of seconds. An approach, which uses the "response/fail" callback to send the next request will provides a much better flexibility.

**Comment by JaroslawLegierski** [comment]
>The traces demonstrates an additional issue:
If always a handshake is used, that for sure limits your bandwidth!
Not sure, I guess the 75 bytes application data in the capture is an error response.
(You may check that with your PSK secret, see [Decrypt messages for PSK Cipher Suites](https://github.com/eclipse-californium/californium/wiki/Logs-and-IP-Capturing-%E2%80%90-How-To-Provide-The-Right-Information#decrypt-messages-for-psk-cipher-suites) how to apply that secret to wireshark).
So it's possible, that the error response is causing the handshakes.

Thank You very much - please find in file bellow decoded coap messages:

[thingy91_coap_only.zip](https://github.com/eclipse-californium/californium/files/10193617/thingy91_coap_only.zip)


>Do you see these handshakes also without congestion control?

I tested Thingy without congestion control and in this case I see only one handshake 

[thingy91_without_congestion.zip](https://github.com/eclipse-californium/californium/files/10193604/thingy91_without_congestion.zip)
[thingy91_without_congestion_coap_only.zip](https://github.com/eclipse-californium/californium/files/10193607/thingy91_without_congestion_coap_only.zip)

It seems that Thingy incorrectly reacts to RST and repeats the handshake

>(I use RFC 9146, see [zephyr-coaps-client - tinydtls](https://github.com/boaks/zephyr-coaps-client).
mbedtls has recently also merged the RFC9146 support, so maybe you also ask zephyr and nordic to go for it.)

I will send this issue to Nordic support

**Comment by boaks** [comment]
Thanks!

It's even an RST. I guess, I have to check that as well. Such exceptions are usually intended to be "converted" in an internal server error, thanks for reporting!

> I tested Thingy without congestion control and in this case I see only one handshake

OK, so, fixing the NullPointerException will help a lot ;).

> It seems that Thingy incorrectly reacts to RST and repeats the handshake

No, a RST is a very hard error! It means, the other side is not able to process the message. 
In that case, I would also try to reconnect to the server. Maybe not that frequently.

**Comment by boaks** [comment]
Just, if you're interested in a fast preview test, checkout PR #2095 .

**Comment by boaks** [comment]
I tested and improved it a little more.
If possible, please test, if that works for you.

**Comment by JaroslawLegierski** [comment]
> I tested and improved it a little more.
> If possible, please test, if that works for you.

I tested the congestion control fix today and it seems that NullPointerException doesn't occur anymore. Thank You very much for the help.

**Comment by boaks** [comment]
AFAIK, it was too short to ask the PMC for the yearly review.
With that, I'm now only able to schedule a bugfix release, but I would like to omit this for this bug. I hope you can work with the snapshot? I don't know, when in the new year the PMC will be able to do the review. As soon we have the go, I would try to schedule the 3.8. release.

**Comment by JaroslawLegierski** [comment]
Yes we can close this issue - Thank You very much again. When do you plan to release version 3.8? As far as i know colleagues working with Leshan are using released cf version not snapshots :(

**Comment by JaroslawLegierski** [comment]
Do you have any news from PMC ?

**Comment by boaks** [comment]
Yes, we passed the review with success.

I currently try to work on the open PRs in order to schedule the 3.8 release.
But I was also busy with tinydtls and currently with some interoperability tests for openssl RawPublicKey.

My current forecast is somehow in 2-3 weeks.

**Comment by boaks** [comment]
See issue #2112

**Comment by JaroslawLegierski** [comment]
Thank You very much for the good news!
