### ISSUE TITLE
I used californium for Android 11, and there is some mistakes, and I don't understand why?

### ISSUE THREAD

**Issue by ZCJYL277** [eclipse-californium/californium#2173]
I used org.eclipse.californium:element-connector:2.0.0-M12 3.2.0 3.5.0 3.7.0 but they are all flase, 
2.0.0 and 3.2.0 told me sendto failed: ENETUNREACH (Network is unreachable)
and 3.5.9 3.7.0 told me these, can you help me reslove this problem?
My App looks like not build the coap connection？
2023-09-05 17:36:33.129 14198-14222/org.ola.sample W/libEGL: EGLNativeWindowType 0x71106382d0 disconnect failed
2023-09-05 17:36:53.537 14198-14262/org.ola.sample W/System.err: [AsyncTask #4] WARN org.eclipse.californium.elements.config.Configuration - cannot write properties to /Californium3.properties: Californium3.properties: open failed: EROFS (Read-only file system)
2023-09-05 17:36:53.544 14198-14262/org.ola.sample W/System.err: [AsyncTask #4] INFO org.eclipse.californium.elements.config.Configuration - defaults added UDP.
2023-09-05 17:36:53.554 14198-14262/org.ola.sample W/System.err: [AsyncTask #4] INFO org.eclipse.californium.elements.config.Configuration - defaults added COAP.
2023-09-05 17:36:53.555 14198-14262/org.ola.sample W/System.err: [AsyncTask #4] INFO org.eclipse.californium.core.network.RandomTokenGenerator - using tokens of 8 bytes in length
2023-09-05 17:36:53.576 14198-14262/org.ola.sample W/System.err: [AsyncTask #4] INFO org.eclipse.californium.ban - Started.
2023-09-05 17:36:53.579 14198-14262/org.ola.sample W/System.err: [AsyncTask #4] INFO org.eclipse.californium.core.network.CoapEndpoint - coap CoapEndpoint uses udp context
2023-09-05 17:36:53.602 14198-14262/org.ola.sample W/System.err: [AsyncTask #4] INFO org.eclipse.californium.elements.config.Configuration - defaults added SYS.
2023-09-05 17:36:53.603 14198-14262/org.ola.sample W/System.err: [AsyncTask #4] INFO org.eclipse.californium.core.network.stack.BlockwiseLayer - coap BlockwiseLayer uses MAX_MESSAGE_SIZE=1024, PREFERRED_BLOCK_SIZE=512, BLOCKWISE_STATUS_LIFETIME=300000, MAX_RESOURCE_BODY_SIZE=8192, BLOCKWISE_STRICT_BLOCK2_OPTION=false
2023-09-05 17:36:53.620 14198-14262/org.ola.sample W/System.err: [AsyncTask #4] INFO org.eclipse.californium.core.network.CoapEndpoint - coap Endpoint [coap://[::]:0] requires an executor to start, using default single-threaded daemon executor
2023-09-05 17:36:53.641 14198-14262/org.ola.sample W/System.err: [AsyncTask #4] INFO org.eclipse.californium.elements.UDPConnector - UDPConnector starts up 1 sender threads and 1 receiver threads
2023-09-05 17:36:53.645 14198-14262/org.ola.sample W/System.err: [AsyncTask #4] INFO org.eclipse.californium.elements.UDPConnector - UDPConnector listening on ::/:::50269, recv buf = 212992, send buf = 212992, recv packet size = 2048
2023-09-05 17:36:53.646 14198-14262/org.ola.sample W/System.err: [AsyncTask #4] INFO org.eclipse.californium.core.network.CoapEndpoint - coap Started endpoint at coap://[::]:50269
2023-09-05 17:36:53.647 14198-14262/org.ola.sample W/System.err: [AsyncTask #4] INFO org.eclipse.californium.core.network.EndpointManager - created implicit endpoint coap://[::]:50269 for coap

java.io.IOException
        at org.ola.sample.SoftAPProvisionActivity$coap_hello_request$1.onError(SoftAPProvisionActivity.java:502)
        at org.eclipse.californium.core.CoapClient$MessageObserverImpl$2.run(CoapClient.java:1779)
        at org.eclipse.californium.core.CoapClient.execute(CoapClient.java:1571)
        at org.eclipse.californium.core.CoapClient$MessageObserverImpl.failed(CoapClient.java:1775)
        at org.eclipse.californium.core.coap.MessageObserverAdapter.onSendError(MessageObserverAdapter.java:131)
        at org.eclipse.californium.core.coap.Message.setSendError(Message.java:1029)
        at org.eclipse.californium.core.coap.Request.setSendError(Request.java:1032)
        at org.eclipse.californium.core.network.CoapEndpoint$SendingCallback.onError(CoapEndpoint.java:1299)
        at org.eclipse.californium.elements.RawData.onError(RawData.java:314)
        at org.eclipse.californium.elements.UDPConnector$Sender.work(UDPConnector.java:526)
        at org.eclipse.californium.elements.UDPConnector$NetworkStageThread.run(UDPConnector.java:442)

**Comment by jvermillard** [comment]
>  /Californium3.properties: Californium3.properties: open failed: EROFS (Read-only file system)

Yeah it's a old design issue with Cf, by default de library read/write configuration files.


Do you have the end of the IOException? like the "caused by" part?

**Comment by boaks** [comment]
Maybe you start with reading the documentation and check the examples.

I'm not sure, if the `Californium3.properties` are the root cause, maybe. The ways that is intended to be used for Android is documented (see [Configuration - Note: For Android](https://github.com/eclipse-californium/californium/blob/main/element-connector/src/main/java/org/eclipse/californium/elements/config/Configuration.java#L194-L198)), one is [](https://github.com/eclipse-californium/californium/blob/main/demo-apps/cf-android/app/src/main/java/org/eclipse/californium/examples/MainActivity.java#L170).

There is also an [android example](https://github.com/eclipse-californium/californium/tree/main/demo-apps/cf-android). That may fail, it's not actively maintained for newer Android versions.

**Comment by ZCJYL277** [comment]
> > /Californium3.properties: Californium3.properties: open failed: EROFS (Read-only file system)
> 
> Yeah it's a old design issue with Cf, by default de library read/write configuration files.
> 
> Do you have the end of the IOException? like the "caused by" part?
this is 3.2.0 IOException
java.io.IOException: java.io.IOException: sendto failed: ENETUNREACH (Network is unreachable)
2023-09-05 16:44:00.597 9372-9491/org.ola.sample W/System.err:     at org.eclipse.californium.core.CoapClient.synchronous(CoapClient.java:1218)
2023-09-05 16:44:00.597 9372-9491/org.ola.sample W/System.err:     at org.eclipse.californium.core.CoapClient.synchronous(CoapClient.java:1190)
2023-09-05 16:44:00.598 9372-9491/org.ola.sample W/System.err:     at org.eclipse.californium.core.CoapClient.post(CoapClient.java:659)
2023-09-05 16:44:00.598 9372-9491/org.ola.sample W/System.err:     at org.ola.sample.SoftAPProvisionActivity$coap_hello_request.doInBackground(SoftAPProvisionActivity.java:480)
2023-09-05 16:44:00.598 9372-9491/org.ola.sample W/System.err:     at org.ola.sample.SoftAPProvisionActivity$coap_hello_request.doInBackground(SoftAPProvisionActivity.java:464)
2023-09-05 16:44:00.598 9372-9491/org.ola.sample W/System.err:     at android.os.AsyncTask$3.call(AsyncTask.java:394)
2023-09-05 16:44:00.598 9372-9491/org.ola.sample W/System.err:     at java.util.concurrent.FutureTask.run(FutureTask.java:266)
2023-09-05 16:44:00.598 9372-9491/org.ola.sample W/System.err:     at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:305)
2023-09-05 16:44:00.598 9372-9491/org.ola.sample W/System.err:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
2023-09-05 16:44:00.598 9372-9491/org.ola.sample W/System.err:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
2023-09-05 16:44:00.598 9372-9491/org.ola.sample W/System.err:     at java.lang.Thread.run(Thread.java:923)
2023-09-05 16:44:00.599 9372-9491/org.ola.sample W/System.err: Caused by: java.io.IOException: sendto failed: ENETUNREACH (Network is unreachable)
2023-09-05 16:44:00.599 9372-9491/org.ola.sample W/System.err:     at libcore.io.IoBridge.maybeThrowAfterSendto(IoBridge.java:586)
2023-09-05 16:44:00.599 9372-9491/org.ola.sample W/System.err:     at libcore.io.IoBridge.sendto(IoBridge.java:554)
2023-09-05 16:44:00.599 9372-9491/org.ola.sample W/System.err:     at java.net.PlainDatagramSocketImpl.send(PlainDatagramSocketImpl.java:125)
2023-09-05 16:44:00.599 9372-9491/org.ola.sample W/System.err:     at java.net.DatagramSocket.send(DatagramSocket.java:721)
2023-09-05 16:44:00.599 9372-9491/org.ola.sample W/System.err:     at org.eclipse.californium.elements.UDPConnector$Sender.work(UDPConnector.java:515)
2023-09-05 16:44:00.600 9372-9491/org.ola.sample W/System.err:     at org.eclipse.californium.elements.UDPConnector$NetworkStageThread.run(UDPConnector.java:434)
2023-09-05 16:44:00.600 9372-9491/org.ola.sample W/System.err: Caused by: android.system.ErrnoException: sendto failed: ENETUNREACH (Network is unreachable)
2023-09-05 16:44:00.600 9372-9491/org.ola.sample W/System.err:     at libcore.io.Linux.sendtoBytes(Native Method)
2023-09-05 16:44:00.601 9372-9491/org.ola.sample W/System.err:     at libcore.io.Linux.sendto(Linux.java:232)
2023-09-05 16:44:00.601 9372-9491/org.ola.sample W/System.err:     at libcore.io.ForwardingOs.sendto(ForwardingOs.java:193)
2023-09-05 16:44:00.602 9372-9491/org.ola.sample W/System.err:     at libcore.io.BlockGuardOs.sendto(BlockGuardOs.java:368)
2023-09-05 16:44:00.602 9372-9491/org.ola.sample W/System.err:     at libcore.io.ForwardingOs.sendto(ForwardingOs.java:193)
2023-09-05 16:44:00.602 9372-9491/org.ola.sample W/System.err:     at libcore.io.IoBridge.sendto(IoBridge.java:552)
2023-09-05 16:44:00.602 9372-9491/org.ola.sample W/System.err: 	... 4 more

**Comment by ZCJYL277** [comment]
> Maybe you start with reading the documentation and check the examples.
> 
> I'm not sure, if the `Californium3.properties` are the root cause, maybe. The ways that is intended to be used for Android is documented (see [Configuration - Note: For Android](https://github.com/eclipse-californium/californium/blob/main/element-connector/src/main/java/org/eclipse/californium/elements/config/Configuration.java#L194-L198)), one is [cf-android Configuration.createStandardWithoutFile()](https://github.com/eclipse-californium/californium/blob/main/demo-apps/cf-android/app/src/main/java/org/eclipse/californium/examples/MainActivity.java#L170).
> 
> There is also an [android example](https://github.com/eclipse-californium/californium/tree/main/demo-apps/cf-android). That may fail, it's not actively maintained for newer Android versions.

**Comment by ZCJYL277** [comment]
> Maybe you start with reading the documentation and check the examples.
> 
> I'm not sure, if the `Californium3.properties` are the root cause, maybe. The ways that is intended to be used for Android is documented (see [Configuration - Note: For Android](https://github.com/eclipse-californium/californium/blob/main/element-connector/src/main/java/org/eclipse/californium/elements/config/Configuration.java#L194-L198)), one is [cf-android Configuration.createStandardWithoutFile()](https://github.com/eclipse-californium/californium/blob/main/demo-apps/cf-android/app/src/main/java/org/eclipse/californium/examples/MainActivity.java#L170).
> 
> There is also an [android example](https://github.com/eclipse-californium/californium/tree/main/demo-apps/cf-android). That may fail, it's not actively maintained for newer Android versions.

Thank you , I will try it.
